# Generated by Django 5.2.3 on 2025-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('matrix_json', models.TextField()),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
