# Generated by Django 5.2.3 on 2025-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningdata',
            name='visualization',
            field=models.ImageField(blank=True, null=True, upload_to='visualizations/'),
        ),
    ]
