# Generated by Django 5.2.3 on 2025-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_user', '0002_screeningdata_visualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningdata',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
